### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by kevinli23** [Playbak-Team/playbak#24]
Clean up and improve the UI

- [x] Change Navbar on video page to default navbar
- [ ] Fix UI for video
- [x] Homepage bg is kinda scuffed, it should stretch instead of repeat (prob also figure out the dynamic bg instead of just 1)
- [x] Also figure out if quotes are feasible or not
- [x] Fix profile UI its pretty clapped

**Comment by kevinli23** [comment]
@daniel-luan I'm planning on taking the UI changes for the homepage + profile and also move the pbsgen on the videos to the profile, is that fine?

**Comment by daniel-luan** [comment]
yep go for it!
